name: Validate PR to QA
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'force-app/**'
    branches: [ Integration ]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - uses: actions/checkout@v4
      - name: Validate on QA
        uses: jawills/sf-deploy@v1.0
        with:
          SFDX_AUTH_URL: ${{ secrets.QA_SFDX_URL}}
          DRY_RUN: true